name: Python CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "0 15 * * 0"

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: # for EnricoMi/publish-unit-test-result-action
      checks: write
      pull-requests: write # for comment_mode
      contents: read # only for private repository
      issues: read # only for private repository
    steps:
      - name: Checkout repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c

      - name: Setup python environment
        uses: ./.github/actions/python-setup
        with:
          python-version: "3.10"
          poetry-version: "1.2.2"

      - name: Lint python code by flake8
        continue-on-error: true
        run: poetry run flake8 src/ tests/ --format junit-xml --output-file report.xml

      - name: Publish flake8 report to PR
        uses: EnricoMi/publish-unit-test-result-action@689e79fca56cb0c3117fbb26e9769b4634a3f521
        with:
          check_name: flake8 results
          junit_files: report.xml

  sast-codeql:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: ["python"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c

      - name: Initialize CodeQL
        uses: github/codeql-action/init@32dc499307d133bb5085bae78498c0ac2cf762d5
        with:
          languages: ${{ matrix.language }}

      - name: Build automatically
        uses: github/codeql-action/autobuild@32dc499307d133bb5085bae78498c0ac2cf762d5

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@32dc499307d133bb5085bae78498c0ac2cf762d5
